version: 1
disable_existing_loggers: false

formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s %(levelprefix)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S %z"
    use_colors: null
  access:
    "()": uvicorn.logging.AccessFormatter
    fmt: "%(asctime)s %(levelprefix)s %(client_addr)s - \"%(request_line)s\" %(status_code)s"
    datefmt: "%Y-%m-%d %H:%M:%S %z"
    use_colors: null

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers: [access]
    level: INFO
    propagate: false

root:
  level: INFO
  handlers: [default]

